// GENERATED by frontend/scripts/decode-unit-sprites.py (commander) from the
// santiontanon/netherearth-disassembly graphic data; do not edit by hand.
// Provenance and licensing: frontend/public/assets/README.md.
// Rows top first: '#' ink, '.' paper, ' ' transparent.
// One frame, no directional facing (Lcd83_render_player always draws
// graphic index 0; see this script's module docstring).

export const COMMANDER_SPRITES: Record<string, readonly string[]> = {
  // L8e3a_iso_additional_graphic_0 (32x30)
  'spectrum.commander': [
    '           .#.  #               ',
    '           .#.###               ',
    '           .#....#              ',
    '          #.#....#              ',
    '          #.#.#...#             ',
    '      #   #.#.#...#             ',
    '    ###   #.#..#...#            ',
    '  ##...###..#..#.###            ',
    '##....##....#...##.#            ',
    '#.....#.....#...#.##            ',
    '##....##...###...### #          ',
    '##.....#....#....#.###          ',
    '###....##.........##..#         ',
    '###..#..#.......###...#         ',
    ' ######.##....##..#....#        ',
    ' ###.##..#..##..##.....#        ',
    '  ##.###.###..##........#       ',
    '  ##.###..#.##...#....###       ',
    '   #.##...##...###..##..#       ',
    '   ###.......##..###....#       ',
    '     ##......#...##...#.#       ',
    '     ##.......#..##.#...#       ',
    '     ###....###..##...##        ',
    '     ###..##..#.# #.##          ',
    '      ####....##  ##            ',
    '      ###...#.#                 ',
    '       ##.#...#                 ',
    '       ##...##                  ',
    '        #.##                    ',
    '        ##                      ',
  ],
};
