"""Decode the Spectrum map-element sprites used for scenery (CR002.5).

Reads the graphic data of santiontanon/netherearth-disassembly
(``netherearth-annotated-data.asm``) and prints
``frontend/src/render/scenery-sprites.ts``.

Evidence (``netherearth-annotated.asm``):

* ``Lcd18_draw_map_cell`` draws a map element (type = low 5 bits of the map
  byte) at the anchor cell of its 2x2 stamp with elevation 0, via
  ``Lcf2d_draw_sprite_to_buffer``; that routine looks up entry
  ``2 * type + (x & 1)`` of ``Ld6e8_additional_isometric_graphic_pointers``
  (the odd entry is the same sprite pre-shifted by 4 pixels).
* Element 17 -> ``La0e2_iso_additional_graphic_27``, 18 ->
  ``La2e6_iso_additional_graphic_29``, 21 -> ``La050_iso_additional_graphic_26``;
  the nuclear blast (``Lba44_robots_handled``) replaces boxes with element
  6 or 7 (debris) -> ``L9d9c_iso_additional_graphic_22`` /
  ``L9ef6_iso_additional_graphic_24``.
* Sprite format ("and-or-bitmap-with-size"): height, width in bytes, then
  per row (bottom row first) per byte an AND mask and an OR byte.

Output rows are top row first: '#' ink (OR bit set), '.' paper (mask
clears, no ink), ' ' transparent (mask keeps the background).

Usage:
    python frontend/scripts/decode-scenery-sprites.py <netherearth-annotated-data.asm> \
        > frontend/src/render/scenery-sprites.ts
"""

import re
import sys

SPRITES = [
    ("spectrum.element_17", 17, "La0e2_iso_additional_graphic_27"),
    ("spectrum.element_18", 18, "La2e6_iso_additional_graphic_29"),
    ("spectrum.element_21", 21, "La050_iso_additional_graphic_26"),
    ("spectrum.element_6", 6, "L9d9c_iso_additional_graphic_22"),
    ("spectrum.element_7", 7, "L9ef6_iso_additional_graphic_24"),
]


def data_bytes(lines: list[str], label: str) -> list[int]:
    out: list[int] = []
    on = False
    for line in lines:
        if line.startswith(label + ":"):
            on = True
            continue
        if on:
            if re.match(r"^L[0-9a-f]{4}", line):
                break
            out += [int(v[1:], 16) for v in re.findall(r"#[0-9a-f]{2}", line.split(";")[0])]
    if not out:
        raise SystemExit(f"label {label} not found")
    return out


def decode(lines: list[str], label: str) -> list[str]:
    b = data_bytes(lines, label)
    h, w, d = b[0], b[1], b[2:]
    rows = []
    for r in range(h):
        s = ""
        for c in range(w):
            mask, ink = d[(r * w + c) * 2], d[(r * w + c) * 2 + 1]
            for bit in range(7, -1, -1):
                if ink >> bit & 1:
                    s += "#"
                elif mask >> bit & 1:
                    s += " "
                else:
                    s += "."
        rows.append(s)
    return rows[::-1]


def main() -> None:
    lines = open(sys.argv[1], encoding="utf-8").read().split("\n")
    print("// GENERATED by frontend/scripts/decode-scenery-sprites.py from the")
    print("// santiontanon/netherearth-disassembly graphic data; do not edit by hand.")
    print("// Provenance and licensing: frontend/public/assets/README.md.")
    print("// Rows top first: '#' ink, '.' paper, ' ' transparent.")
    print("")
    print("export const SCENERY_SPRITES: Record<string, readonly string[]> = {")
    for sid, element, label in SPRITES:
        rows = decode(lines, label)
        print(f"  // map element {element}: {label} ({len(rows[0])}x{len(rows)})")
        print(f"  '{sid}': [")
        for row in rows:
            print(f"    '{row}',")
        print("  ],")
    print("};")


if __name__ == "__main__":
    main()
