"""Decode the Spectrum map-element sprites used for scenery (CR002.5).

Reads the graphic data of santiontanon/netherearth-disassembly
(``netherearth-annotated-data.asm``) and prints
``frontend/src/render/scenery-sprites.ts``.

Evidence (``netherearth-annotated.asm``):

* ``Lcd18_draw_map_cell`` draws a map element (type = low 5 bits of the map
  byte) at the anchor cell of its 2x2 stamp with elevation 0, via
  ``Lcf2d_draw_sprite_to_buffer``; that routine looks up entry
  ``2 * type + (x & 1)`` of ``Ld6e8_additional_isometric_graphic_pointers``
  (the odd entry is the same sprite pre-shifted by 4 pixels).
* Element 17 -> ``La0e2_iso_additional_graphic_27``, 18 ->
  ``La2e6_iso_additional_graphic_29``, 21 -> ``La050_iso_additional_graphic_26``;
  the nuclear blast (``Lba44_robots_handled``) replaces boxes with element
  6 or 7 (debris) -> ``L9d9c_iso_additional_graphic_22`` /
  ``L9ef6_iso_additional_graphic_24``.
* Sprite format ("and-or-bitmap-with-size"): height, width in bytes, then
  per row (bottom row first) per byte an AND mask and an OR byte.

Output rows are top row first: '#' ink (OR bit set), '.' paper (mask
clears, no ink), ' ' transparent (mask keeps the background).

Usage:
    python frontend/scripts/decode-scenery-sprites.py <netherearth-annotated-data.asm> \
        > frontend/src/render/scenery-sprites.ts
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _netherearth_gfx import decode  # noqa: E402

SPRITES = [
    ("spectrum.box_low", 17, "La0e2_iso_additional_graphic_27"),
    ("spectrum.box_high", 18, "La2e6_iso_additional_graphic_29"),
    ("spectrum.fence", 21, "La050_iso_additional_graphic_26"),
    ("spectrum.debris_a", 6, "L9d9c_iso_additional_graphic_22"),
    ("spectrum.debris_b", 7, "L9ef6_iso_additional_graphic_24"),
    # CR-robots: the two wall-segment graphics war bases and factories are
    # built from (see decode-unit-sprites.py / warbase-sprites.ts docstring).
    ("spectrum.wall_low", 15, "L9914_iso_additional_graphic_18"),
    ("spectrum.wall_high", 16, "L9b18_iso_additional_graphic_20"),
]


def main() -> None:
    lines = open(sys.argv[1], encoding="utf-8").read().split("\n")
    print("// GENERATED by frontend/scripts/decode-scenery-sprites.py from the")
    print("// santiontanon/netherearth-disassembly graphic data; do not edit by hand.")
    print("// Provenance and licensing: frontend/public/assets/README.md.")
    print("// Rows top first: '#' ink, '.' paper, ' ' transparent.")
    print("")
    print("export const SCENERY_SPRITES: Record<string, readonly string[]> = {")
    for sid, element, label in SPRITES:
        rows = decode(lines, label)
        print(f"  // map element {element}: {label} ({len(rows[0])}x{len(rows)})")
        print(f"  '{sid}': [")
        for row in rows:
            print(f"    '{row}',")
        print("  ],")
    print("};")


if __name__ == "__main__":
    main()
