"""Decode the Spectrum title music score (#272).

Reads the code listing of santiontanon/netherearth-disassembly
(``netherearth-annotated.asm``) and prints
``frontend/src/audio/title-score.ts``.

Evidence (``netherearth-annotated.asm``):

* ``Lc4a7_title_music_loop`` is a software sound chip: a tight loop runs two
  pulse oscillators whose periods sit in self-modifying bytes
  (``Lc4ed``/``Lc4f3`` for channel 1, ``Lc4d0``/``Lc4d6`` for channel 2) and
  whose on/off byte is ``ld a, 24`` / ``ld a, 0`` (``Lc4ef``/``Lc4d2``).
* ``Lc4fd_title_music_loop_interrupt`` runs once per frame (50 Hz) and steps
  three scripts: channel 1 from ``Lc678``, channel 2 from ``Lc702`` and the
  percussion from ``Lc665``.
* Note events (``Lc528`` / ``Lc53b``): a byte >= 9 is the oscillator period,
  followed by a duration in frames. The period byte is written verbatim to the
  counter and ``rrca rrca / and #3f`` (period // 4) to the pulse width.
* Command events are the bytes 0..8 and index the jump tables at ``Lc54f`` /
  ``Lc56e``: 0 nop, 1 jump, 2 call, 3/7/8 set percussion pointer, 4 activate
  channel, 5 silence channel, 6 return. Commands 1, 2, 3, 7 and 8 take a
  little-endian address operand; 0, 4, 5 and 6 stand alone.
* Percussion (``Lc5db_music_percussion``) is its own byte stream: ``01 lo hi``
  is a go-to, otherwise ``count, instrument`` repeats one instrument for
  ``count`` frames, where instrument 0 is ``Lc608_drum1``, 2 is
  ``Lc616_tone_drum`` (which takes a third byte, its period) and any other
  value is ``Lc5f0_drum2``.

The interpreter for this bytecode lives in ``frontend/src/audio/score.ts``, so
this script only lifts the bytes and the entry points out of the listing. The
data is addressed absolutely (the scripts jump and call by address), so the
bytes are emitted as one blob with its base address, exactly as it sits in
Spectrum memory.

Usage:

    python frontend/scripts/decode-music.py <netherearth-annotated.asm> \\
        > frontend/src/audio/title-score.ts
"""

import re
import sys

# The music data is one contiguous run of `db` directives, from the percussion
# loops to the last channel-2 subroutine.
FIRST_LABEL = "Lc665_percussion_loops"
END_LABEL = "Lc820_title_color_cycle"

LABEL_RE = re.compile(r"^(L([0-9a-f]{4})[0-9a-z_]*):")
DB_RE = re.compile(r"^\s+db\s+(.*?)\s*(?:;.*)?$")


def decode(lines: list[str]) -> tuple[int, list[int]]:
    """Return (base address, bytes) for the music data block."""
    start = next(i for i, l in enumerate(lines) if l.startswith(FIRST_LABEL + ":"))
    end = next(i for i, l in enumerate(lines) if l.startswith(END_LABEL + ":"))

    base = int(FIRST_LABEL[1:5], 16)
    data: list[int] = []
    for line in lines[start:end]:
        label = LABEL_RE.match(line)
        if label:
            # Every label in the block names its own address, so it doubles as
            # a check that nothing but `db` bytes was picked up on the way.
            want = int(label.group(2), 16)
            got = base + len(data)
            if want != got:
                raise SystemExit(f"{label.group(1)}: at #{got:04x}, expected #{want:04x}")
            continue
        db = DB_RE.match(line)
        if db:
            for item in db.group(1).split(","):
                data.append(int(item.strip().lstrip("#"), 16))
    return base, data


def main() -> None:
    lines = open(sys.argv[1], encoding="utf-8").read().split("\n")
    base, data = decode(lines)

    print("// GENERATED by frontend/scripts/decode-music.py from the")
    print("// santiontanon/netherearth-disassembly listing; do not edit by hand.")
    print("// Provenance and licensing: frontend/public/assets/README.md.")
    print("//")
    print("// The title music score, verbatim, as one blob at its Spectrum address.")
    print("// score.ts walks it; see decode-music.py for the bytecode.")
    print("")
    print(f"/** Address the blob starts at, so the scripts' operands index into it. */")
    print(f"export const SCORE_BASE = 0x{base:04x};")
    print("")
    print("/** Entry point of the percussion script (Lc665_percussion_loops). */")
    print("export const PERCUSSION_START = 0xc665;")
    print("/** Entry point of the channel 1 script (Lc678_music_event_table_channel1). */")
    print("export const CHANNEL1_START = 0xc678;")
    print("/** Entry point of the channel 2 script (Lc702_music_event_table_channel2). */")
    print("export const CHANNEL2_START = 0xc702;")
    print("")
    print(f"export const SCORE_BYTES: readonly number[] = [")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        print(f"  {row},")
    print("];")


if __name__ == "__main__":
    main()
