"""Decode the Spectrum robot-piece and commander sprites (owner-directed
extension of the CR002.5 scenery pipeline, 2026-09-22).

Reads the graphic data of santiontanon/netherearth-disassembly
(``netherearth-annotated-data.asm``) and prints either
``frontend/src/render/robot-sprites.ts`` or
``frontend/src/render/commander-sprites.ts``.

Evidence (``netherearth-annotated.asm``):

Robot pieces
------------
``Lcefd_draw_robot_piece_to_buffer`` draws each selected piece (bit test of
``ROBOT_STRUCT_PIECES``) by looking up ``Ld6c8_piece_direction_graphic_indices``
at ``4 * piece + direction`` (piece 0 = bipod .. 7 = electronics; direction is
one of 4 cardinal directions decoded from the robot's one-hot
``ROBOT_STRUCT_DIRECTION``), adding 22 to skip past the 44-entry
``Ld6e8_additional_isometric_graphic_pointers`` table, and drawing the sprite
at (that index - 22) * 2 of the following ``Ld740_isometric_graphic_pointers``
table (58 pointers, confirmed by its own inline per-piece comments: "tracks",
"bipod", "antigrav", "cannon", "missiles", "phaser", "nuclear"). This script
decodes direction 0 of each piece (the first column of
``Ld6c8_piece_direction_graphic_indices``); see the direction table below for
the other 3 columns, which are not currently wired into the frontend because
the WebSocket snapshot protocol does not expose a robot facing/direction
field (a presentation-only gap, not a gameplay one -- see
``_specs/open-questions.md``).

Full 4-direction table (piece: dir0, dir1, dir2, dir3), each entry is a label
in ``Ld740_isometric_graphic_pointers``:

* bipod:       L6c8a, L6c8a, L6e32, L6e32
* tracks:      L6980, L6980, L6afe, L6afe
* anti_grav:   L6fcc, L6fcc, L6fcc, L6fcc
* cannon:      L7112, L729e, L7446, L75ee
* missile:     L7750, L7750, L78ce, L78ce
* phaser:      L7a5a, L7be6, L7d80, L7f1a
* nuclear:     L808a, L808a, L808a, L808a
* electronics: L8224, L8348, L846c, L8590

Commander
---------
``Lcd83_render_player`` (the on-foot commander figure, distinct from a robot)
always draws graphic index 0 (``xor a``) of
``Ld6e8_additional_isometric_graphic_pointers``, i.e.
``L8e3a_iso_additional_graphic_0`` -- one frame, no directional facing, no
selectable pieces.

Usage:
    python frontend/scripts/decode-unit-sprites.py robot <data.asm> \\
        > frontend/src/render/robot-sprites.ts
    python frontend/scripts/decode-unit-sprites.py commander <data.asm> \\
        > frontend/src/render/commander-sprites.ts
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _netherearth_gfx import decode  # noqa: E402

# Direction-0 label per robot piece (see module docstring for all 4 columns).
ROBOT_PIECE_SPRITES = [
    ("bipod", "L6c8a_iso_graphic_4"),
    ("tracks", "L6980_iso_graphic_0"),
    ("anti_grav", "L6fcc_iso_graphic_8"),
    ("cannon", "L7112_iso_graphic_10"),
    ("missile", "L7750_iso_graphic_18"),
    ("phaser", "L7a5a_iso_graphic_22"),
    ("nuclear", "L808a_iso_graphic_30"),
    ("electronics", "L8224_iso_graphic_32"),
]

COMMANDER_SPRITE = ("spectrum.commander", "L8e3a_iso_additional_graphic_0")


def emit_robot(lines: list[str]) -> None:
    print("// GENERATED by frontend/scripts/decode-unit-sprites.py (robot) from the")
    print("// santiontanon/netherearth-disassembly graphic data; do not edit by hand.")
    print("// Provenance and licensing: frontend/public/assets/README.md.")
    print("// Rows top first: '#' ink, '.' paper, ' ' transparent.")
    print("// Direction 0 only (see the script's docstring for the other 3 cardinal")
    print("// directions the disassembly encodes per piece; not wired in yet -- the")
    print("// snapshot protocol carries no robot facing field).")
    print("import type { ModuleId } from './robot.ts';")
    print("")
    print("export const ROBOT_SPRITES: Record<ModuleId, readonly string[]> = {")
    for module_id, label in ROBOT_PIECE_SPRITES:
        rows = decode(lines, label)
        print(f"  // {label} (direction 0), {len(rows[0])}x{len(rows)}")
        print(f"  {module_id}: [")
        for row in rows:
            print(f"    '{row}',")
        print("  ],")
    print("};")


def emit_commander(lines: list[str]) -> None:
    sid, label = COMMANDER_SPRITE
    rows = decode(lines, label)
    print("// GENERATED by frontend/scripts/decode-unit-sprites.py (commander) from the")
    print("// santiontanon/netherearth-disassembly graphic data; do not edit by hand.")
    print("// Provenance and licensing: frontend/public/assets/README.md.")
    print("// Rows top first: '#' ink, '.' paper, ' ' transparent.")
    print("// One frame, no directional facing (Lcd83_render_player always draws")
    print("// graphic index 0; see this script's module docstring).")
    print("")
    print("export const COMMANDER_SPRITES: Record<string, readonly string[]> = {")
    print(f"  // {label} ({len(rows[0])}x{len(rows)})")
    print(f"  '{sid}': [")
    for row in rows:
        print(f"    '{row}',")
    print("  ],")
    print("};")


def main() -> None:
    kind = sys.argv[1]
    lines = open(sys.argv[2], encoding="utf-8").read().split("\n")
    if kind == "robot":
        emit_robot(lines)
    elif kind == "commander":
        emit_commander(lines)
    else:
        raise SystemExit(f"unknown kind {kind!r}; expected 'robot' or 'commander'")


if __name__ == "__main__":
    main()
